# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from omniwheel_control/wheels_trans.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class wheels_trans(genpy.Message):
  _md5sum = "c432407a8349c63fa0f07653bd392f4a"
  _type = "omniwheel_control/wheels_trans"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32[] wID
int32 wcenterx
int32 wcentery
float64 angle
"""
  __slots__ = ['wID','wcenterx','wcentery','angle']
  _slot_types = ['int32[]','int32','int32','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       wID,wcenterx,wcentery,angle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(wheels_trans, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.wID is None:
        self.wID = []
      if self.wcenterx is None:
        self.wcenterx = 0
      if self.wcentery is None:
        self.wcentery = 0
      if self.angle is None:
        self.angle = 0.
    else:
      self.wID = []
      self.wcenterx = 0
      self.wcentery = 0
      self.angle = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.wID)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.pack(pattern, *self.wID))
      _x = self
      buff.write(_get_struct_2id().pack(_x.wcenterx, _x.wcentery, _x.angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.wID = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 16
      (_x.wcenterx, _x.wcentery, _x.angle,) = _get_struct_2id().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.wID)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.wID.tostring())
      _x = self
      buff.write(_get_struct_2id().pack(_x.wcenterx, _x.wcentery, _x.angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.wID = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      _x = self
      start = end
      end += 16
      (_x.wcenterx, _x.wcentery, _x.angle,) = _get_struct_2id().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2id = None
def _get_struct_2id():
    global _struct_2id
    if _struct_2id is None:
        _struct_2id = struct.Struct("<2id")
    return _struct_2id
