// Generated by gencpp from file omniwheel_control/move_base.msg
// DO NOT EDIT!


#ifndef OMNIWHEEL_CONTROL_MESSAGE_MOVE_BASE_H
#define OMNIWHEEL_CONTROL_MESSAGE_MOVE_BASE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace omniwheel_control
{
template <class ContainerAllocator>
struct move_base_
{
  typedef move_base_<ContainerAllocator> Type;

  move_base_()
    : v_right(0)
    , v_left(0)
    , v_back(0)  {
    }
  move_base_(const ContainerAllocator& _alloc)
    : v_right(0)
    , v_left(0)
    , v_back(0)  {
  (void)_alloc;
    }



   typedef int64_t _v_right_type;
  _v_right_type v_right;

   typedef int64_t _v_left_type;
  _v_left_type v_left;

   typedef int64_t _v_back_type;
  _v_back_type v_back;





  typedef boost::shared_ptr< ::omniwheel_control::move_base_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::omniwheel_control::move_base_<ContainerAllocator> const> ConstPtr;

}; // struct move_base_

typedef ::omniwheel_control::move_base_<std::allocator<void> > move_base;

typedef boost::shared_ptr< ::omniwheel_control::move_base > move_basePtr;
typedef boost::shared_ptr< ::omniwheel_control::move_base const> move_baseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::omniwheel_control::move_base_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::omniwheel_control::move_base_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace omniwheel_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'omniwheel_control': ['/home/chenxin/workspace/omniwheeltest/workspace/src/omniwheel_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::omniwheel_control::move_base_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omniwheel_control::move_base_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omniwheel_control::move_base_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omniwheel_control::move_base_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omniwheel_control::move_base_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omniwheel_control::move_base_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::omniwheel_control::move_base_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7eb46e0f2c9f6ac4de66b4a1727ce26";
  }

  static const char* value(const ::omniwheel_control::move_base_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7eb46e0f2c9f6acULL;
  static const uint64_t static_value2 = 0x4de66b4a1727ce26ULL;
};

template<class ContainerAllocator>
struct DataType< ::omniwheel_control::move_base_<ContainerAllocator> >
{
  static const char* value()
  {
    return "omniwheel_control/move_base";
  }

  static const char* value(const ::omniwheel_control::move_base_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::omniwheel_control::move_base_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 v_right\n\
int64 v_left\n\
int64 v_back\n\
";
  }

  static const char* value(const ::omniwheel_control::move_base_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::omniwheel_control::move_base_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.v_right);
      stream.next(m.v_left);
      stream.next(m.v_back);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct move_base_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::omniwheel_control::move_base_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::omniwheel_control::move_base_<ContainerAllocator>& v)
  {
    s << indent << "v_right: ";
    Printer<int64_t>::stream(s, indent + "  ", v.v_right);
    s << indent << "v_left: ";
    Printer<int64_t>::stream(s, indent + "  ", v.v_left);
    s << indent << "v_back: ";
    Printer<int64_t>::stream(s, indent + "  ", v.v_back);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OMNIWHEEL_CONTROL_MESSAGE_MOVE_BASE_H
