// Generated by gencpp from file omniwheel_control/wheels_trans.msg
// DO NOT EDIT!


#ifndef OMNIWHEEL_CONTROL_MESSAGE_WHEELS_TRANS_H
#define OMNIWHEEL_CONTROL_MESSAGE_WHEELS_TRANS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace omniwheel_control
{
template <class ContainerAllocator>
struct wheels_trans_
{
  typedef wheels_trans_<ContainerAllocator> Type;

  wheels_trans_()
    : wID()
    , wcenterx(0)
    , wcentery(0)
    , angle(0.0)  {
    }
  wheels_trans_(const ContainerAllocator& _alloc)
    : wID(_alloc)
    , wcenterx(0)
    , wcentery(0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _wID_type;
  _wID_type wID;

   typedef int32_t _wcenterx_type;
  _wcenterx_type wcenterx;

   typedef int32_t _wcentery_type;
  _wcentery_type wcentery;

   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::omniwheel_control::wheels_trans_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::omniwheel_control::wheels_trans_<ContainerAllocator> const> ConstPtr;

}; // struct wheels_trans_

typedef ::omniwheel_control::wheels_trans_<std::allocator<void> > wheels_trans;

typedef boost::shared_ptr< ::omniwheel_control::wheels_trans > wheels_transPtr;
typedef boost::shared_ptr< ::omniwheel_control::wheels_trans const> wheels_transConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::omniwheel_control::wheels_trans_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::omniwheel_control::wheels_trans_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace omniwheel_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'omniwheel_control': ['/home/chenxin/workspace/omniwheeltest/workspace/src/omniwheel_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::omniwheel_control::wheels_trans_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omniwheel_control::wheels_trans_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omniwheel_control::wheels_trans_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omniwheel_control::wheels_trans_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omniwheel_control::wheels_trans_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omniwheel_control::wheels_trans_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::omniwheel_control::wheels_trans_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c432407a8349c63fa0f07653bd392f4a";
  }

  static const char* value(const ::omniwheel_control::wheels_trans_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc432407a8349c63fULL;
  static const uint64_t static_value2 = 0xa0f07653bd392f4aULL;
};

template<class ContainerAllocator>
struct DataType< ::omniwheel_control::wheels_trans_<ContainerAllocator> >
{
  static const char* value()
  {
    return "omniwheel_control/wheels_trans";
  }

  static const char* value(const ::omniwheel_control::wheels_trans_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::omniwheel_control::wheels_trans_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] wID\n\
int32 wcenterx\n\
int32 wcentery\n\
float64 angle\n\
";
  }

  static const char* value(const ::omniwheel_control::wheels_trans_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::omniwheel_control::wheels_trans_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wID);
      stream.next(m.wcenterx);
      stream.next(m.wcentery);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wheels_trans_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::omniwheel_control::wheels_trans_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::omniwheel_control::wheels_trans_<ContainerAllocator>& v)
  {
    s << indent << "wID[]" << std::endl;
    for (size_t i = 0; i < v.wID.size(); ++i)
    {
      s << indent << "  wID[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.wID[i]);
    }
    s << indent << "wcenterx: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wcenterx);
    s << indent << "wcentery: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wcentery);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OMNIWHEEL_CONTROL_MESSAGE_WHEELS_TRANS_H
